"""rename-todo-to-task

Revision ID: 176d584d7539
Revises: 738565e1bc75
Create Date: 2025-07-10 10:55:05.987746

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "176d584d7539"
down_revision: Union[str, None] = "738565e1bc75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_uuid"), "tasks", ["uuid"], unique=False)
    op.drop_index(op.f("ix_todo_lists_uuid"), table_name="todo_lists")
    op.drop_table("todo_lists")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "todo_lists",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("completed", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "expires_at",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("todo_lists_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("todo_lists_pkey")),
    )
    op.create_index(op.f("ix_todo_lists_uuid"), "todo_lists", ["uuid"], unique=False)
    op.drop_index(op.f("ix_tasks_uuid"), table_name="tasks")
    op.drop_table("tasks")
    # ### end Alembic commands ###
