"""create-task-source

Revision ID: 44e0e7791d37
Revises: 176d584d7539
Create Date: 2025-07-14 00:29:15.764247

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44e0e7791d37"
down_revision: str | None = "176d584d7539"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "EMAIL",
                "CALENDAR",
                "SLACK",
                "TEAMS",
                "DISCORD",
                "GITHUB_ISSUE",
                "GITHUB_PR",
                "JIRA",
                "TRELLO",
                "ASANA",
                "NOTION",
                "LINEAR",
                "CLICKUP",
                "OTHER",
                name="sourcetype",
            ),
            nullable=False,
        ),
        sa.Column("source_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("extra_data", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_sources_source_id"), "task_sources", ["source_id"], unique=False)
    op.create_index(
        op.f("ix_task_sources_source_type"),
        "task_sources",
        ["source_type"],
        unique=False,
    )
    op.create_index(op.f("ix_task_sources_uuid"), "task_sources", ["uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_sources_uuid"), table_name="task_sources")
    op.drop_index(op.f("ix_task_sources_source_type"), table_name="task_sources")
    op.drop_index(op.f("ix_task_sources_source_id"), table_name="task_sources")
    op.drop_table("task_sources")
    # ### end Alembic commands ###
