"""add stripe customer id to users table

Revision ID: 6e543f3fb891
Revises: 655e04c7f2b0
Create Date: 2025-08-20 16:42:37.923873

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e543f3fb891"
down_revision: str | None = "655e04c7f2b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Subscriptionsテーブルは作成しない（Stripe APIから直接取得するため）
    op.drop_index(
        op.f("idx_chat_messages_user_role_created"),
        table_name="chat_messages",
        postgresql_where="((role)::text = 'user'::text)",
    )
    op.drop_index(op.f("idx_chat_messages_thread_created_desc"), table_name="chat_messages")
    op.create_index("idx_chat_messages_thread_created_desc", "chat_messages", ["thread_id", "created_at"], unique=False)
    op.drop_index(op.f("idx_chat_threads_user_updated_desc"), table_name="chat_threads")
    op.create_index("idx_chat_threads_user_updated_desc", "chat_threads", ["user_id", "updated_at"], unique=False)
    op.add_column("users", sa.Column("stripe_customer_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f("ix_users_stripe_customer_id"), "users", ["stripe_customer_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_stripe_customer_id"), table_name="users")
    op.drop_column("users", "stripe_customer_id")
    op.drop_index("idx_chat_threads_user_updated_desc", table_name="chat_threads")
    op.create_index(
        op.f("idx_chat_threads_user_updated_desc"),
        "chat_threads",
        ["user_id", sa.literal_column("updated_at DESC")],
        unique=False,
    )
    op.drop_index("idx_chat_messages_thread_created_desc", table_name="chat_messages")
    op.create_index(
        op.f("idx_chat_messages_thread_created_desc"),
        "chat_messages",
        ["thread_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_chat_messages_user_role_created"),
        "chat_messages",
        ["thread_id", "created_at"],
        unique=False,
        postgresql_where="((role)::text = 'user'::text)",
    )
    # Note: Subscriptionsテーブル関連の処理は削除（存在しないため）
    # ### end Alembic commands ###
