"""add_chat_thread_and_message_models

Revision ID: af62fb93b70c
Revises: f1a2b3c4d5e6
Create Date: 2025-08-16 14:58:00.266596

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af62fb93b70c"
down_revision: str | None = "f1a2b3c4d5e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_threads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_chat_threads_user_id", "chat_threads", ["user_id"], unique=False)
    op.create_index("idx_chat_threads_uuid", "chat_threads", ["uuid"], unique=False)
    op.create_index(op.f("ix_chat_threads_user_id"), "chat_threads", ["user_id"], unique=False)
    op.create_index(op.f("ix_chat_threads_uuid"), "chat_threads", ["uuid"], unique=False)
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("thread_id", sa.Integer(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["chat_threads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_chat_messages_created_at", "chat_messages", ["created_at"], unique=False)
    op.create_index("idx_chat_messages_role", "chat_messages", ["role"], unique=False)
    op.create_index("idx_chat_messages_thread_created", "chat_messages", ["thread_id", "created_at"], unique=False)
    op.create_index("idx_chat_messages_thread_id", "chat_messages", ["thread_id"], unique=False)
    op.create_index("idx_chat_messages_uuid", "chat_messages", ["uuid"], unique=False)
    op.create_index(op.f("ix_chat_messages_created_at"), "chat_messages", ["created_at"], unique=False)
    op.create_index(op.f("ix_chat_messages_role"), "chat_messages", ["role"], unique=False)
    op.create_index(op.f("ix_chat_messages_thread_id"), "chat_messages", ["thread_id"], unique=False)
    op.create_index(op.f("ix_chat_messages_uuid"), "chat_messages", ["uuid"], unique=False)
    op.drop_constraint("uq_ai_chat_usage_user_date", "ai_chat_usage", type_="unique")
    op.create_unique_constraint("uq_user_date", "ai_chat_usage", ["user_id", "usage_date"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_date", "ai_chat_usage", type_="unique")
    op.create_unique_constraint("uq_ai_chat_usage_user_date", "ai_chat_usage", ["user_id", "usage_date"])
    op.drop_index(op.f("ix_chat_messages_uuid"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_thread_id"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_role"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_created_at"), table_name="chat_messages")
    op.drop_index("idx_chat_messages_uuid", table_name="chat_messages")
    op.drop_index("idx_chat_messages_thread_id", table_name="chat_messages")
    op.drop_index("idx_chat_messages_thread_created", table_name="chat_messages")
    op.drop_index("idx_chat_messages_role", table_name="chat_messages")
    op.drop_index("idx_chat_messages_created_at", table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_chat_threads_uuid"), table_name="chat_threads")
    op.drop_index(op.f("ix_chat_threads_user_id"), table_name="chat_threads")
    op.drop_index("idx_chat_threads_uuid", table_name="chat_threads")
    op.drop_index("idx_chat_threads_user_id", table_name="chat_threads")
    op.drop_table("chat_threads")
    # ### end Alembic commands ###
