"""add_task_priority_field

Revision ID: d6dfb3322f2a
Revises: 2dc03f02d485
Create Date: 2025-07-31 13:12:51.689823

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd6dfb3322f2a'
down_revision: str | None = '2dc03f02d485'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    task_priority_enum = sa.Enum('HIGH', 'MIDDLE', 'LOW', name='taskpriority')
    task_priority_enum.create(op.get_bind())

    op.add_column('tasks', sa.Column('priority', task_priority_enum, nullable=True))
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_column('tasks', 'priority')

    # Drop the enum type
    task_priority_enum = sa.Enum('HIGH', 'MIDDLE', 'LOW', name='taskpriority')
    task_priority_enum.drop(op.get_bind())
    # ### end Alembic commands ###
