"""add_ai_chat_usage_logs_table

Revision ID: e89ba24a8c2b
Revises: d6dfb3322f2a
Create Date: 2025-08-02 15:00:14.349924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e89ba24a8c2b'
down_revision: Union[str, None] = 'd6dfb3322f2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_chat_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('usage_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'usage_date', name='uq_user_usage_date')
    )
    op.create_index(op.f('ix_ai_chat_usage_logs_usage_date'), 'ai_chat_usage_logs', ['usage_date'], unique=False)
    op.create_index(op.f('ix_ai_chat_usage_logs_user_id'), 'ai_chat_usage_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_chat_usage_logs_user_id'), table_name='ai_chat_usage_logs')
    op.drop_index(op.f('ix_ai_chat_usage_logs_usage_date'), table_name='ai_chat_usage_logs')
    op.drop_table('ai_chat_usage_logs')
    # ### end Alembic commands ###
